# Dependencies
markdown:         kramdown
highlighter:      rouge
redcarpet:
  extensions : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            "馬丁"
tagline:          "筆記"
description:      "程式筆記"
url:              https://matin5.github.com
baseurl:          /

author:
  name:           "Martin Wu"
  url:            https://matin5.github.com

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/matin5

# Gems
gems: [jekyll-paginate, jekyll-gist]
